---
- name: install node_exporter on rpi cluster nodes
  hosts: all
  become: true
  gather_facts: true
  
  vars:
    inc_prometheus_config: true
    
  tasks:

    - name: install node exporter
      include_role:
        name: install_node_exporter
    
    - name: configure prometheus
      include_role:
        name: prometheus_config
      when: inc_prometheus_config|bool
      run_once: true
