---
# configure trip points for poe hat fan on ubuntu

- name: transfer udev rules file
  template:
    src: 50-rpi-fan.rules.j2
    dest: /etc/udev/rules.d/50-rpi-fan.rules
    owner: root
    group: root
    mode: 0644

- name: reload udev rules
  shell: >
    udevadm control --reload-rules && udevadm trigger

- name: get cpu temp trip points
  shell: cat /etc/udev/rules.d/50-rpi-fan.rules | grep ATTR | awk 'BEGIN { FS =  "="} ; {print $2}'
  register: trip_results

- name: cpu temp trip point results (in millidegrees)
  debug:
    msg:
      - 'tp3 temp: {{trip_results.stdout_lines[0]}}'
      - 'tp3 hyst: {{trip_results.stdout_lines[1]}}'
      - 'tp2 temp: {{trip_results.stdout_lines[2]}}'
      - 'tp2 hyst: {{trip_results.stdout_lines[3]}}'
      - 'tp1 temp: {{trip_results.stdout_lines[4]}}'
      - 'tp1 hyst: {{trip_results.stdout_lines[5]}}'
      - 'tp0 temp: {{trip_results.stdout_lines[6]}}'
      - 'tp0 hyst: {{trip_results.stdout_lines[7]}}'
  
- name: reboot cluster
  reboot:
    msg: reboot initiated to apply changes
    test_command: uptime
  when: reboot_var|bool
  
- name: action complete
  debug:
    msg: "PoE fan adjustments complete"
    
- name: reboot required
  debug: 
    msg: "reboot required for changes to take effect."
  when: not reboot_var|bool

